server.port=8081
spring.application.name=kafka-producer-service

# Both brokers listed for redundancy, if one is down, producer connects to the other
spring.kafka.bootstrap-servers=localhost:9092,localhost:9192

# Metadata refresh interval: how often producer re-fetches cluster info (default 5 min)
spring.kafka.producer.properties.metadata.max.age.ms=300000

spring.kafka.producer.acks=all

#---------------SERIALIZER-------------
# for Key
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Value: JsonSerializer,auto-converts Java objects to JSON bytes
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#---------------RECORD ACCUMULATOR-------
# Batching, wait 20ms to collect more messages before sending
spring.kafka.producer.properties.linger.ms=20

# Max batch size, send when batch reaches 32KB (even if linger.ms hasn't expired)
spring.kafka.producer.properties.batch.size=32768

# Total buffer memory for all batches: 32MB (if full, send() will get blocked till space created)
spring.kafka.producer.properties.buffer.memory=33554432

# Max time send() blocks if buffer is full (default 60s)
spring.kafka.producer.properties.max.block.ms=60000


#---------------COMPRESSION-------

# compresses entire batch before sending
spring.kafka.producer.properties.compression.type=snappy


#---------------SENDER THREAD-------

# Retry on transient failures (network timeout, leader change, etc.)
spring.kafka.producer.retries=3

# Max in-flight requests ? up to 5 batches can be sent without waiting for ack
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5


#---------------IDEMPOTENCY-------

# Prevents duplicate messages on retry AND preserves ordering with in-flight > 1
# When true, each message gets PID (Producer ID) + sequence number
# Broker rejects out-of-order sequences ? forces correct ordering even with retries
# Also forces: acks=all, retries=MAX_INT internally
spring.kafka.producer.properties.enable.idempotence=true







